# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
boot.kernelModules = [ "kvm-intel" "cifs"  ];
boot.extraModulePackages = [ ];
boot.kernelParams = [ "resume = UUID = 2109b751-9337-4462-a33c-9ed5fb9f7a53" "video=VGA-1:800x600@60e video=VGA-2:800x600@60e"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cda69583-7ee0-48da-99e3-4ccdb8c3e766";
      fsType = "btrfs";
      options = [ "subvol=@nixos_r" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3f5e6807-7f61-4939-ada5-4cbe5060c266";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F5C-0954";
      fsType = "vfat";
    };

  fileSystems."/mnt/share" = {
      device = "//nixsos";
      fsType = "cifs";
      options = let
#        # this line prevents hanging on network split
         automount_opts = "x-systemd.automount,user,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
      in ["${automount_opts},credentials=/etc/nixos/smb-secrets"];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2109b751-9337-4462-a33c-9ed5fb9f7a53"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
#boot.resumeDevice  = "/dev/disk/by-uuid/ec18bb62-5739-4851-86ba-9db45b922288";
#boot.resumeDevice = mkOption { example =  "/dev/disk/by-uuid/ec18bb62-5739-4851-86ba-9db45b922288"; };
}
